<img src="https://github.com/markokct/DSB-Unit-02-EDA-with-Pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Exercise: descriptive statistics in `pandas`

_Authors: David Asboth_

---

## Learning Objectives

After this lesson, students will be able to:

- Explore descriptive statistics of a data set using pandas

# Lesson Guide

This notebook helps students practice:

- Calculating descriptive statistics in `pandas`
- Doing group-level analysis in `pandas`
    - Doing "split-apply-combine" with `groupby`
    - Aggregating and summarizing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

The question we want to answer is: **How do LEGO products vary across different types/themes?**

## Guided questions

***Remember to check back to notebooks 1 and 2 - they contain everything you need!***

Let's import the data and preview it.

*Note: if you place the `lego.csv` file in the same folder as this notebook, you'll need to change the filepath to just `"lego.csv"`*

In [6]:
import pandas as pd

lego = pd.read_csv("https://raw.githubusercontent.com/markokct/DSB-Unit-02-EDA-with-Pandas/refs/heads/main/data/lego.csv")
lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

In [7]:
lego.info

<bound method DataFrame.info of          Set_ID                     Name  Year      Theme    Theme_Group  \
0          75-1            PreSchool Set  1975  PreSchool     Pre-school
1          77-1            PreSchool Set  1975  PreSchool     Pre-school
2         077-1           Pre-School Set  1975      Duplo     Pre-school
3          78-1            PreSchool Set  1975  PreSchool     Pre-school
4          78-3                Basic Set  1975  Samsonite        Vintage
...         ...                      ...   ...        ...            ...
14931  854242-1        Creeper Key Chain  2023       Gear  Miscellaneous
14932  854243-1          Steve Key Chain  2023       Gear  Miscellaneous
14933  854244-1         Piglin Key Chain  2023       Gear  Miscellaneous
14934  854245-1   Fennec Shand Key Chain  2023       Gear  Miscellaneous
14935  854246-1  Scout Trooper Key Chain  2023       Gear  Miscellaneous

                   Subtheme Category        Packaging  Num_Instructions  \
0                       NaN   Normal  {Not specified}                 0
1                       NaN   Normal  {Not specified}                 0
2                       NaN   Normal  {Not specified}                 0
3                       NaN   Normal  {Not specified}                 0
4                 Basic set   Normal              Box                 0
...                     ...      ...              ...               ...
14931  Key Chains/Minecraft     Gear              Tag                 0
14932  Key Chains/Minecraft     Gear              Tag                 0
14933  Key Chains/Minecraft     Gear              Tag                 0
14934  Key Chains/Star Wars     Gear              Tag                 0
14935  Key Chains/Star Wars     Gear              Tag                 0

          Availability  Pieces  Minifigures  Owned  Rating  USD_MSRP  \
0      {Not specified}    16.0          NaN   10.0     0.0       NaN
1      {Not specified}    20.0          NaN   11.0     0.0       NaN
2      {Not specified}    21.0          NaN   10.0     0.0       NaN
3      {Not specified}    32.0          NaN    8.0     0.0       NaN
4      {Not specified}   330.0          NaN   10.0     0.0       NaN
...                ...     ...          ...    ...     ...       ...
14931   LEGO exclusive     NaN          NaN    2.0     0.0      5.99
14932   LEGO exclusive     NaN          NaN    2.0     0.0      5.99
14933   LEGO exclusive     NaN          NaN    2.0     0.0      5.99
14934   LEGO exclusive     NaN          NaN   88.0     0.0      5.99
14935   LEGO exclusive     NaN          NaN  107.0     0.0      5.99

       Total_Quantity  Current_Price
0                 NaN            NaN
1                 NaN            NaN
2                 0.0            NaN
3                 NaN            NaN
4                 0.0            NaN
...               ...            ...
14931             NaN            NaN
14932             NaN            NaN
14933             NaN            NaN
14934             NaN            NaN
14935             NaN            NaN

[14936 rows x 17 columns]>

#### 1. Find the "theme group" that has the biggest sets, i.e. that has the highest average number of pieces

In [9]:
# average_pieces_by_theme_group = lego.groupby('Theme_Group')['Pieces'].mean()
# biggest_sets_theme_group = average_pieces_by_theme_group.idxmax()
# max_average_pieces = average_pieces_by_theme_group.max()

# print(f"The 'theme group' with the biggest sets (highest average number of pieces) is: {biggest_sets_theme_group}")
# print(f"With an average of {max_average_pieces:.2f} pieces.")

The 'theme group' with the biggest sets (highest average number of pieces) is: Art and crafts
With an average of 775.28 pieces.

In [23]:
highest_pieces_theme_group = lego.groupby('Theme_Group')['Pieces'].mean().sort_values(ascending=False).head(1)
highest_pieces_theme_group

Theme_Group
Art and crafts    775.276596
Name: Pieces, dtype: float64

#### 2. How does that group compare to the average number of pieces in the entire data set?

In [26]:
round(lego['Pieces'].mean(), 2)

np.float64(237.94)

In [15]:
# overall_average_pieces = lego['Pieces'].mean()

# print(f"The 'Art and crafts' theme group has an average of {max_average_pieces:.2f} pieces.")
# print(f"The overall average number of pieces in the entire dataset is: {overall_average_pieces:.2f}.")

# if max_average_pieces > overall_average_pieces:
#     print(f"This means the 'Art and crafts' theme group has significantly more pieces than the overall average.")
# elif max_average_pieces < overall_average_pieces:
#     print(f"This means the 'Art and crafts' theme group has fewer pieces than the overall average.")
# else:
#     print(f"This means the 'Art and crafts' theme group has the same number of pieces as the overall average.")

The 'Art and crafts' theme group has an average of 775.28 pieces.
The overall average number of pieces in the entire dataset is: 237.94.
This means the 'Art and crafts' theme group has significantly more pieces than the overall average.

#### 3. Within this theme group, how does the number of pieces compare per individual theme?

*Hint: you'll need to filter your data before doing the aggregation!*

In [30]:
lego[lego['Theme_Group'] == "Art and crafts"].groupby("Theme")["Pieces"].mean()

Theme
Art     3836.692308
Dots     283.938272
Name: Pieces, dtype: float64

In [12]:
# art_and_crafts_df = lego[lego['Theme_Group'] == 'Art and crafts']
# average_pieces_by_theme_in_art_and_crafts = art_and_crafts_df.groupby('Theme')['Pieces'].mean()

# print("Average number of pieces per individual theme within 'Art and crafts' group:")
# print(average_pieces_by_theme_in_art_and_crafts.sort_values(ascending=False))

Average number of pieces per individual theme within 'Art and crafts' group:
Theme
Art     3836.692308
Dots     283.938272
Name: Pieces, dtype: float64

#### 4. Find the most expensive set in the "Creator Expert" theme

In [32]:
lego[lego["Theme"] == "Creator Expert"].sort_values(by="Current_Price", ascending=False).head(1)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
10936,10251-1,Brick Bank,2016,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,2380.0,5.0,20785.0,4.4,169.99,23.0,597.62

In [14]:
# creator_expert_df = lego[lego['Theme'] == 'Creator Expert']
# most_expensive_creator_expert = creator_expert_df.loc[creator_expert_df['USD_MSRP'].idxmax()]

# print(f"The most expensive set in the 'Creator Expert' theme is: {most_expensive_creator_expert['Name']}")
# print(f"With a price of: ${most_expensive_creator_expert['USD_MSRP']:.2f}")

The most expensive set in the 'Creator Expert' theme is: Roller Coaster
With a price of: $379.99

#### 5. BONUS - can you figure out the average price AND the maximum number of pieces for each **theme group** in a single command?

*Hint: look at the `.agg` command...*

In [33]:
lego.groupby('Theme_Group').agg({
    'Current_Price': 'mean',
    'Pieces': 'max'
})

                  Current_Price   Pieces
Theme_Group
Action/Adventure      87.133444   6163.0
Art and crafts        30.882232  11695.0
Basic                 22.600684   2847.0
Constraction          80.970243    856.0
Educational          133.753232   4900.0
Girls                 57.785984    450.0
Historical           210.434185   1601.0
Junior                32.721408    480.0
Licensed             112.382881   7541.0
Miscellaneous         44.914558   4502.0
Model making         122.405318  10001.0
Modern day            64.486840   2010.0
Pre-school            36.467305    640.0
Racing                55.071398   1484.0
Technical            113.706339   4108.0
Vintage              154.824400   1112.0

In [16]:
# lego.groupby('Theme_Group').agg({
#     'USD_MSRP': 'mean',
#     'Pieces': 'max'
# })

                    USD_MSRP   Pieces
Theme_Group
Action/Adventure   37.755258   6163.0
Art and crafts     32.803953  11695.0
Basic              21.241799   2847.0
Constraction       16.384541    856.0
Educational       136.818235   4900.0
Girls              35.836154    450.0
Historical         35.032857   1601.0
Junior             21.958254    480.0
Licensed           50.749095   7541.0
Miscellaneous      18.936033   4502.0
Model making       72.632910  10001.0
Modern day         37.465186   2010.0
Pre-school         30.572418    640.0
Racing             26.766702   1484.0
Technical          80.586856   4108.0
Vintage                  NaN   1112.0

## Reflection

Based on your initial findings, what answers can you give to the initial business question?

> **How do LEGO products vary across different types/themes?**